version: "3"
services:

  jenkins:
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    container_name: jenkins

    volumes:
      - ./jenkins:/var/jenkins_home:rw

  artifactory:
    image: mattgruter/artifactory
    ports:
      - "9090:8080"
    container_name: artifactory
    volumes:
      - ./artifactory:/artifactory:rw
